


const ActionTypes ={
  REGISTER_REQUEST:"REGISTER_REQUEST",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_FAIL : "REGISTER_FAIL",
  LOGIN_SUCCESS :"LOGIN_SUCCESS",
  LOGIN_FAIL : "LOGIN_FAIL",
    LOGOUT : "LOGOUT",
 
};

export default ActionTypes